### ISSUE TITLE
RICHKA Web API

### ISSUE THREAD

**Issue by hiroki8080** [cocktailmake/cocktailmake.github.io#17]
Create a post about the abstract of WebAPI.

**Comment by shishimaru** [comment]
@hiroki8080 

Could you improve the visibility below with a table ?
![image](https://user-images.githubusercontent.com/570090/94752478-52a6c080-03c6-11eb-833f-edc700942784.png)

Could you make a sequence diagram as image file and replace ?
![image](https://user-images.githubusercontent.com/570090/94752545-81bd3200-03c6-11eb-86a7-363f730588d0.png)

It is easy to create the sequence diagram with PlantURML as https://enk.backlog.jp/wiki/REC/Sequence+diagrams.

**Comment by hiroki8080** [comment]
@shishimaru 

Thank you for your review.
I fixed it.
However, the table was originally displayed in Markdown format as a preview.
How did you check it out?

If you check it with the preview function of Visual Studio Code, it will be displayed as follows.

<img width="848" alt="スクリーンショット 2020-10-07 13 57 47" src="https://user-images.githubusercontent.com/3500772/95298021-5e0e5600-08b6-11eb-9a7a-64156bc2f2b9.png">

**Comment by shishimaru** [comment]
@hiroki8080 
As described at https://github.com/cocktailmake/cocktailmake.github.io/tree/src, you can run the blog server on your local.
```
$ nikola auto -b
```

**Comment by hiroki8080** [comment]
@shishimaru 
I investigated why tables and plantuml diagrams are not drawn correctly.
The result was as follows.

・plantuml doesn't seem to work well on the local server of markdown + nicola + plantuml.
I changed this to a png diagram.

・The table definition of markdown is output correctly, but it seems that css is not applied
It seems that bootstrap3 css is installed, do you think you need to customize css?
Or do you think it's better to plot the table as well?

**Comment by shishimaru** [comment]
Done
