### ISSUE TITLE
Page speed improvement of videos on RICHKA GUI

### ISSUE THREAD

**Issue by tunglt** [cocktailmake/cocktailmake.github.io#24]
Our past effort to make the page speed of video list and format list on top and edit page faster with integrating a delayed loading of video contents.

**Comment by shishimaru** [comment]
@tunglt 
Thank you for describing the improvement points. Please let me share the feedback of 2 points below.

**Feedback 1:**
It is difficult to understand only with the text description.
Could you add some figures or screenshots to support the descriptions ?

**Feedback 2:**

The section below is a general thing and could you remove ?
If the numbers (1), (2), (4), (5), (6), (7) are not referred from anything, please delete.
It is good to describe only the technically interesting part even if it is small.

```
** Pagination and search
    Number of videos and images are large. Displaying all of them is too slow, so we limited the number of videos and images.

    Namely, we apply the improvement for (1), (2), (5) with number is 10; for (4) with number is 20; (6), (7) only has a video so it's no need.
```
